version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        image: nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/server/django_static
            - ./compose/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend
    django:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile
        image: django
        volumes:
            - ./.envs/.django  
            - ./.envs/.postgres    
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - .:/app
            - static_volume:/app/backend/server/django_static
        expose:
            - 8000        

volumes:
    static_volume: {}