version: '2'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume: {}

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        image: nginx
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/server/django_static
            - ./compose/nginx/development:/etc/nginx/conf.d
        depends_on: 
            - django
    django: &django
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile
        image: django
        depends_on:
            - postgres
        volumes:
            - .:/app
            - static_volume:/app/backend/server/django_static
        env_file:
            - ./.envs/.django  
            - ./.envs/.postgres
        entrypoint: /app/compose/django/wsgi-entrypoint.sh
        expose:
            - 8000
    postgres:
        build:
            context: .
            dockerfile: ./compose/postgres/Dockerfile
        image: postgres
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.postgres